[package]
name = "blink-http-core"
version = "1.2.0"
authors = ["Jonas F. Franke <me@binaryblazer.me>"]
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
wasm-bindgen = "0.2"
