name: Node.js Package Publish

on:
  release:
    types: [created]

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.0.1
      - run: bun install

  publish-npm:
    needs: check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Rust and Cargo
        run: |
          sudo apt update
          sudo apt install -y curl
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
      - run: npm install -g bun
      - run: bun install
      - run: bun run build
      - name: Publish to npm
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            npm publish --tag latest --provenance --access public
          elif [ "${{ github.ref }}" == "refs/heads/canary" ]; then
            npm publish --tag canary --provenance --access public
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}