name: Node.js Package Publish

on:
  release:
    types: [created]

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.0.1
      - run: bun install

  publish-npm:
    needs: check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Rust and Cargo
        run: |
          sudo apt update
          sudo apt install -y curl
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
      - run: npm install -g bun
      - run: bun install
      - run: bun run build
      - name: Determine the branch
        id: branch
        run: echo ::set-output name=branch::${GITHUB_REF#refs/heads/}
      - name: Set npm tag
        id: npm_tag
        run: |
          if [ "${{ steps.branch.outputs.branch }}" == "main" ]; then
            echo ::set-output name=tag::latest
          elif [ "${{ steps.branch.outputs.branch }}" == "canary" ]; then
            echo ::set-output name=tag::canary
          else
            echo ::set-output name=tag::${{ steps.branch.outputs.branch }}
          fi
      - name: Publish to npm
        run: npm publish --provenance --access public --tag ${{ steps.npm_tag.outputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
